import './globals.css'
import Navigation from '@/components/navigation/navigation.component'
import Footer from '@/components/footer/footer.component'
import { Radio_Canada } from "next/font/google"


const radioCanada = Radio_Canada({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={radioCanada.className}>
        <Navigation/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
